- docs/usage.rst
- src/aiodynamo/client.py
- src/aiodynamo/models.py
- tests/integration/conftest.py
- tests/integration/test_client.py
Trying to address https://github.com/HENNGE/aiodynamo/issues/21
Still fails from my laptop...
> try to test on aws with higher throughput

- docs/advanced.rst
- src/aiodynamo/credentials.py
- tests/unit/test_credentials.py
Reduces useless calls and iterations in ChainCredentials.
> Ignore disabled credential providers in ChainCredentials

- .circleci/config.yml
- pyproject.toml
To my best understanding of `pyproject.toml`, as flavoured by `poetry` 😅
> Optional deps

- readme.md
- tests/integration/test_client.py
> better readme and fixed badge

- docs/changelog.rst
- src/aiodynamo/credentials.py
- src/aiodynamo/sign.py
> don't leak metadata or session tokens in logs

- src/aiodynamo/client.py
- src/aiodynamo/errors.py
- src/aiodynamo/http/aiohttp.py
- src/aiodynamo/http/base.py
- src/aiodynamo/http/httpx.py
wrap client errors for retries to work.
> wrap client errors

- src/aiodynamo/client.py
> retry on internal dynamodb errors

- src/aiodynamo/expressions.py
- src/aiodynamo/types.py
- tests/unit/test_expressions.py
> fix hash key path encoding

- docs/usage.rst
- src/aiodynamo/credentials.py
The static credentials part from #56
> Add StaticCredentials

- src/aiodynamo/credentials.py
- tests/unit/test_credentials.py
> Role ARN support in InstanceMetadata Credentials

- .circleci/config.yml
- mypy.ini
- pyproject.toml
- src/aiodynamo/client.py
- src/aiodynamo/credentials.py
- src/aiodynamo/errors.py
- src/aiodynamo/expressions.py
- src/aiodynamo/http/aiohttp.py
- src/aiodynamo/http/base.py
- src/aiodynamo/http/httpx.py
- src/aiodynamo/models.py
- src/aiodynamo/sign.py
- src/aiodynamo/types.py
Passes mypy with strict enabled, but needs some ugly workarounds and way too much `Any` (mostly in internal code) for my taste. But it should still be useful for users since this would make their mypy check their usage of aiodynamo.
> Add full typing

- docs/development.rst
- docs/usage.rst
- pyproject.toml
- src/aiodynamo/client.py
- src/aiodynamo/credentials.py
- src/aiodynamo/http/aiohttp.py
- tests/integration/conftest.py
- tests/integration/test_client.py
- tests/unit/test_credentials.py
- tests/unit/test_utils.py
Based off #66, adding tests and supporting custom file locations and profile names.
> Support File credentials

- src/aiodynamo/credentials.py
#65 
brief implement without any profiles
> credential file support

- benchmarks/deserialize/utils.py
> fix byte encoding for benchmark dummy data util

- src/aiodynamo/utils.py
> Update deserialize to use mapping

- src/aiodynamo/client.py
- src/aiodynamo/credentials.py
- src/aiodynamo/expressions.py
- src/aiodynamo/http/base.py
- src/aiodynamo/sign.py
> don't use from typing import *

- docs/changelog.rst
- src/aiodynamo/credentials.py
- tests/unit/test_credentials.py
> Support session tokens in FileCredentials

- benchmarks/deserialize/utils.py
- benchmarks/query/bench_botocore.py
- benchmarks/query/fill_db.py
- pyproject.toml
- src/aiodynamo/models.py
- tests/integration/test_client.py
should also fix the click import errors on ci
> upgrade black

- .github/workflows/workflow.yml
Closes #129 
Integration tests now run with both dynalite and dynamodb-local.
Unfortunately service can't be set with matrix so the code has to be duplicated
> Fix integration tests not running on Github Actions

- .github/workflows/workflow.yml
To prevent broken jobs from running indefinitely.
> Set timeout-minutes of 10 min to all jobs

- .readthedocs.yaml
- .readthedocs.yml
- pyproject.toml
readthedocs now [requires a config and changed the config a bit](https://blog.readthedocs.com/migrate-configuration-v2/), trying to get it to work.
> upgrade readthedocs config

- src/aiodynamo/client.py
- tests/integration/test_client.py
duplicate of #154 to try to get CI checks to run
> Update maximum operations per transaction to 100

- .pre-commit-config.yaml
- docs/usage.rst
- src/aiodynamo/expressions.py
- src/aiodynamo/utils.py
- tests/unit/test_expressions.py
These can be useful when trying to figure out why a complex expression isn't doing what you think it should. 
Also added a pre-commit hook for the unit tests since those run super quick anyway. and tried to make the docs a tiny bit nicer too lok at (at some point probably need to change the theme or something, quite a few of these pages look very crowded)
> Add debug helper to Condition and UpdateExpression

- src/aiodynamo/credentials.py
- tests/unit/test_credentials.py
Extract token refresher from MetadataCredentials and re-use it in imdsv2
> Better token refresh
