src/aiodynamo/models.py, tests/unit/test_models.py
The value cache for ExpressionAttributeValues in UpdateExpression.encode had a bug where 0 and False as well as 1 and True would get mixed up.
Fixes #6
=> Fixed UpdateExpression.encode value cache

src/aiodynamo/client.py, tests/integration/test_client.py
describe_time_to_live response does not return ["TimeToLiveDescription"] ["AttributeName"] when the status is disabled.
=> Fixed KeyError on describe_time_to_live response

benchmarks/deserialize/README.md, benchmarks/deserialize/bench_aiodynamo.py, benchmarks/deserialize/bench_boto3.py, benchmarks/deserialize/utils.py, docs/changelog.rst, pyproject.toml, src/aiodynamo/client.py, src/aiodynamo/types.py, src/aiodynamo/utils.py, tests/unit/test_utils.py
local results from the benchmarks:
```
❯ poetry run python -mpyperf stats aiodynamo.json
Total duration: 2 min 14.1 sec
Start date: 2020-02-18 15:29:37
End date: 2020-02-18 15:32:47
Raw value minimum: 709 ms
Raw value maximum: 942 ms
Number of calibration run: 1
Number of run with values: 40
Total number of run: 41
Number of warmup per run: 1
Number of value per run: 3
Loop iterations per value: 1
Total number of values: 120
Minimum:         709 ms
Median +- MAD:   871 ms +- 35 ms
Mean +- std dev: 839 ms +- 76 ms
Maximum:         942 ms
0th percentile: 709 ms (-16% of the mean) -- minimum
5th percentile: 717 ms (-15% of the mean)
25th percentile: 747 ms (-11% of the mean) -- Q1
50th percentile: 871 ms (+4% of the mean) -- median
75th percentile: 899 ms (+7% of the mean) -- Q3
95th …
```
=> added faster dynamodb item deserializer

docs/advanced.rst, src/aiodynamo/client.py, src/aiodynamo/credentials.py, src/aiodynamo/errors.py
seems like boto is using 10 minutes for mandatory token refresh, so I adopted the same deadline. 
Added a first class Exception for expired tokens
Retry on expired tokens if the token could be invalidated
Added more logging
=> more logging, better token expiration handling

src/aiodynamo/client.py, tests/integration/test_client.py
Bug in `scan` where providing a ProjectionExpression but no FilterExpression would lead to an invalid payload.
=> Scan with projection only

readme.md
* `httpx` and `aiohttp` quick start samples on the front page 
* slightly more prominent `2x faster`
Close #31
=> httpx and aiohttp examples on the front page, close #31

src/aiodynamo/client.py, src/aiodynamo/errors.py, src/aiodynamo/http/aiohttp.py, src/aiodynamo/http/base.py, src/aiodynamo/http/httpx.py
Remove all the extra info from `RequestFailed`, the caller can still get it from the chained exception. Add super simple retry logic to `send_request` retrying all `RequestFailed` errors.
=> make RequestFailed simpler, add retry

docs/changelog.rst, src/aiodynamo/client.py, src/aiodynamo/expressions.py, tests/integration/test_client.py, tests/unit/test_expressions.py
fixes `put_item` and `delete_item` with conditions that do not carry values.
refactors how parameters are injected into the payload to prevent these kind of bugs in the future.
=> Fix put_item and delete_item conditions without values

src/aiodynamo/expressions.py, tests/integration/test_client.py
Fixes #41
The right hand side of comparisons (including `size(...)` comparisons) can be other fields (which isn't really mentioned in their [docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html)).
=> Fix comparison condition expressions

src/aiodynamo/client.py, src/aiodynamo/errors.py, tests/integration/test_client.py
Currently, when no credentials can be found, the client fails with a strange `AttributeError`. This change will make the client retry on credentials resolving failure and raise an appropriate error if no credentials could ever be fetched.
=> Improved the way the client handles no key being returned from credentials

docs/concepts.rst, src/aiodynamo/expressions.py, src/aiodynamo/utils.py, tests/integration/conftest.py, tests/integration/test_client.py
Fixes #48, removes special handling for empty strings and bytes.
Sadly, DynamoDB emulators seem to not yet support this so tests are marked as xfail for now.
=> remove empty string handling

docs/usage.rst, src/aiodynamo/client.py, src/aiodynamo/models.py, tests/integration/test_client.py
Adds two new APIs to both `Client` and `Table`: `query_single_page` and `scan_single_page`, both taking the same arguments as `query` and `scan` respectively. Unlike `query` and `scan`, they do not return an async iterator over items, but instead a `Page` which has a `List` of items and the `LastEvaluatedKey`. They can be used in cases where manual de-pagination is desired, such as returning items from DynamoDB via a paginated API.
=> Add API to query/scan single DynamoDB pages

docs/changelog.rst, src/aiodynamo/client.py, tests/integration/test_client.py
This was motivated by our real-life use case. We sometimes need to limit counting to preserve latency and Dynamo resources. I tried using `query_single_page` but it doesn't support count queries, so I just added `limit` to `count`.
=> Count limits

docs/usage.rst, src/aiodynamo/client.py, src/aiodynamo/models.py, src/aiodynamo/types.py, tests/integration/conftest.py, tests/integration/test_client.py
Currently aiodynamo creates tables using the provisioned billing mode. DynamoDB also supports pay_per_request where no throughput config is provided. This PR is backwards compatible, but also adds the support to provide a `billing_mode` parameter to `create_table`. The `throughput` parameter has been changed to optional as the pay_per_request billing mode doesn't use it.
PS. I'd be very grateful if you could also add the `hacktoberfest-accepted` label to this PR once it is accepted so that it can be counted as a hacktoberfest PR. Thanks :)
=> Add support for pay_per_request billing mode during table creation

src/aiodynamo/errors.py
For #70 
`ResourceInUseException` is returned when trying to create a table that already exists... (maybe the assumption is that table is being used right now).
ran into this with `dynalite`.
=> handle ResourceInUseException

src/aiodynamo/expressions.py, tests/unit/test_expressions.py
Fixes #110 
Instances of F can now be compared for equality if their paths match and
provide a reasonable repr.
The changes to UpdateExpression included here are because implementing
__eq__ for F means that setting the same field twice in an update
expresssion would ignore one of the values. This changes the behaviour
of `F("a").set("a") & F("a").set("b")` which currently raises a
(DynamoDB-side) error, but no longer raised one after implementing
__eq__. Switching from Dict[F, T] to List[Tuple[F, T]] preserves the
current behaviour and invalid update expressions correctly raise an
error.
=> Add __eq__ and __repr__ to aiodynamo.expressions.F

benchmarks/query/README.md, benchmarks/query/fill_db.py, benchmarks/query/utils.py
- drop unused RNAGE_KEY_NAME in benchmarks
- fix the data filler
=> [BENCH_]RANGE_KEY_NAME was not used

src/aiodynamo/client.py, tests/unit/test_client.py
On errors (eg throttling), no exception would be raised, causing higher level APIs to raise key errors.
=> Fix new-http error handling

src/aiodynamo/http/httpx.py
Now `asyncio.TimeoutError` is handled in the client logic. But `httpx` wrapper raises `httpx.TimeoutException`.
This pull request convert the exception and make the client be able to handle timeouts in `httpx`.
ref.) `httpx` timeout exceptions
https://github.com/encode/httpx/blob/master/httpx/_exceptions.py#L7-L11
ref.) Custom HTTP Client Adaptor document
https://github.com/HENNGE/aiodynamo/blob/2e6c4716a3ac9fe5669bbdcaa73e6bbe0f73cfbb/docs/advanced.rst
=> Raise asyncio.TimeoutError on httpx.TimeoutException

src/aiodynamo/expressions.py, tests/integration/test_client.py
DynamoDB KeyConditionExpressions only allow a limited number of
operators when constraining the range/sort key. aiodynamo incorrectly
included too many operators which are available in FilterExpressions,
this removes the unsupported ones and adds tests for the supported ones.
=> Removed unsupported operations from RangeKey

.github/workflows/workflow.yml
As mentioned on #53 issue, to be able to support dynamo transaction we need another dynamo emulator because dynalite does not support transaction.
So this PR is adding a step on CI that run tests against a localstack dynamodb.
=> Add localstack pytest step on CI workflow

docs/usage.rst, src/aiodynamo/client.py, src/aiodynamo/operations.py, tests/integration/test_client.py
Adding support for [TransactGetItems](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactGetItems.html)
=> Add transact get items method to client

src/aiodynamo/errors.py, tests/unit/test_errors.py
The value of the __type key in body of the error responses from dynamodb local does not have the com.amazonaws.dynamodb.v20120810# prefix.
An example of a ConditionalCheckFailedException:
```
{"__type": "ConditionalCheckFailedException", "message": "The conditional request failed"}
````
=> Support typed exceptions with dynamodb-local.

src/aiodynamo/credentials.py, tests/unit/test_credentials.py
Adds support for using AWS_PROFILE env var in the credentials chain.  
This behavior is more in line with the behavior expected by users coming from boto3 or aiobotocore.
Added a unit test to cover this feature.
Relates to: Issue #139
=> add AWS_PROFILE env var to credentials chain

pyproject.toml
Dependency resolution took a long time because poetry chose the wrong version of urllib3.
Specifying the urllib3 version solve the resolution.
=> Fix poetry lock running forever

.github/workflows/workflow.yml, docs/conf.py, pyproject.toml
3.7 is EOL'd
Sphinx upgrade makes it so our complex signatures look _a lot_ better than before.
Old:
New:
=> Upgrade dependencies, drop 3.7 support, add 3.11 support

.github/workflows/release.yml
As with AAPNS, this will automatically publish a new pypi release when a Github release is created.
=> Add GHA for PyPi release

.pre-commit-config.yaml, docs/changelog.rst, src/aiodynamo/credentials.py, tests/unit/test_credentials.py, tests/unit/test_utils.py
Refreshable had a timing bug where refreshing the token could result in an invalid state if invalidate() was called at the same time. This is due to the Event Loop being able to schedule other coroutines to run between the current value being set in _refresh() and the value being checked in get(). By moving the assignment from _refresh() to get(), no other coroutines can run between the setting and checking, preventing the class from ending up in an invalid state.
ChainCredentials would needlessly check many candidates every time, even if it had already done so previously. Since running code cannot move to different environments, this check is unneccessary and inefficient, so instead ChainCredentials now remembers when a provider has succeeded and will only try that one again.
=> Fix timing bug in Refreshable, optimize ChainCredentials

src/aiodynamo/expressions.py, tests/integration/test_client.py
Turns out the attribute type filter simply doesn't work at the moment 😅. The [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html#Expressions.OperatorsAndFunctions.Syntax) is quite clear on the subject that the attribute type tag needs to be parametrized.
=> Fix attribute type filter

src/aiodynamo/client.py, src/aiodynamo/models.py
This will also omit the calls to describe table if `wait_for_active` is enabled in implementations which immediately activate the table on creation.
=> Return table description from create table

src/aiodynamo/expressions.py, src/aiodynamo/utils.py, tests/unit/test_expressions.py
Previously, AND and OR conditions with more than two elements would lead to nested ANDs and ORs, making the resulting expression much more complicated and harder to read/understand. This change flattens AndCondition and OrCondition objects when they're combined.
Context: had to debug some complicated conditions (~10 AND's) and the extreme nesting makes it super hard to debug/read them.
~Not a _huge_ fan of the name `MinLen2AppendOnlyList` so if someone has a better suggestion I'd love to hear it.~
=> Flatten AND and OR conditions

src/aiodynamo/errors.py
The `cancellation_reasons` have a mismatched type when initializing, and this change fixes it. Additionally, it has been changed to use `Optional` instead of `Union[T, None]` because they are equivalent but `Optional` has a shorter name.
=> fix a type mismatch for TransactionCanceled

src/aiodynamo/client.py, src/aiodynamo/utils.py
I'd like to make the logging for aiodynamo louder at times for debugging
or to generally see in application logs when a throttle or a timeout or
something happened. For that, I need to set the log level to debug, but
this also enables request and response payload logging which becomes
very noisy and also smears potentially unwanted data into my log
streams.
I made two other loggers so the levels for those two things can be
set at a different level to all the other logging done by aiodynamo.
=> Separate request and response logging into other named loggers.

.github/workflows/workflow.yml, pyproject.toml
Because these two libs are required to run the test cases, making it (a tiny bit) easier to set up a new development environment.
=> add httpx and aiohttp as dev dependencies

src/aiodynamo/errors.py
Add more pre-defined error types from the [official document](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html).  
Also, I added a `SerializationException`, which is not mentioned in the document but is found in dynalite. Someone on Stack Overflow also encountered this error when using DynamoDB, so I assume it is being used by DynamoDB as well.  
Related to #70
=> add more error types

.github/workflows/workflow.yml, docs/development.rst, pyproject.toml, tests/integration/conftest.py, tests/integration/test_client.py, tests/unit/test_utils.py
I think I found a bug in dynalite, so for now I just have a test until I have more information. 
EDIT: slight scope creep, added compatibility for pytest-xdist because on my machine running the full test suite on three implementations took longer than one minute, with `-nauto` it's down to 30 seconds again.
=> Add test for update with IN condition
